# Generated by Django 4.2.9 on 2024-01-11 07:43

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lungAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_name', models.CharField(choices=[('amphoric_respiration', 'Amphoric Respiration'), ('asthma', 'Asthma'), ('bronchial_respiration', 'Bronchial Respiration'), ('bronchovesicular_respiration', 'Bronchovesicular Respiration'), ('coarse_crackles', 'Coarse Crackles'), ('covid-19', 'COVID-19'), ('diminished_vesicular_respiration', 'Diminished Vesicular Respiration'), ('fine_crackles', 'Fine Crackles'), ('gurgling_rhonchi', 'Gurgling Rhonchi'), ('harsh_respiration', 'Harsh Respiration'), ('left-sided_pneumothorax', 'Left-side Pneumothorax'), ('pleural_friction_rub', 'Pleural Friction Rub'), ('pneumonia', 'Pneumonia'), ('rhonchi', 'Rhonchi'), ('right-sided_pneumothorax', 'Right-sided Pneumothorax'), ('stridor', 'Stridor'), ('vesicular_respiration', 'Vesicular Respiration'), ('wheezes', 'Wheezzes')], max_length=50)),
                ('sound_type', models.CharField(choices=[('LLB', 'Type LLB'), ('LLF', 'Type LLF'), ('LMB', 'Type LMB'), ('LUB', 'Type LUB'), ('LUF', 'Type LUF'), ('RLB', 'Type RLB'), ('RLF', 'Type RLF'), ('RMB', 'Type RMB'), ('RMF', 'Type RMF'), ('RUB', 'Type RUB'), ('RUF', 'Type RUF')], max_length=3)),
                ('audio_file', models.FileField(storage=app.models.OverwriteStorage(), upload_to='app/static/audio/lungs/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>/')),
            ],
        ),
    ]
