# Generated by Django 4.2.9 on 2024-01-11 10:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lungaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartaudio',
            name='audio_file',
            field=models.FileField(storage=app.models.OverwriteStorage(), upload_to='heart/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='lungaudio',
            name='audio_file',
            field=models.FileField(storage=app.models.OverwriteStorage(), upload_to='lungs/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>/'),
        ),
    ]
