# Generated by Django 4.2.9 on 2024-01-18 04:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_heartaudio_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='heartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartrate', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='heartaudio',
            name='audio_file',
            field=models.FileField(storage=app.models.OverwriteStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='lungaudio',
            name='audio_file',
            field=models.FileField(storage=app.models.OverwriteStorage(), upload_to=''),
        ),
    ]
