# Generated by Django 4.2.9 on 2024-01-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_heartnavbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='heartSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
