# Generated by Django 4.2.9 on 2024-01-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_heartsound'),
    ]

    operations = [
        migrations.DeleteModel(
            name='heartNavButton',
        ),
    ]
