# Generated by Django 4.2.9 on 2024-01-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_heartnavbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='breathRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breathrate', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='heartSound',
        ),
    ]
