# Generated by Django 4.2.9 on 2024-01-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_breathrate_delete_heartsound'),
    ]

    operations = [
        migrations.DeleteModel(
            name='breathRate',
        ),
        migrations.DeleteModel(
            name='heartRate',
        ),
    ]
